**Preproceesing of Tweets **

*   removing extra space
*   removing punctuations
*   lower case ,e.t.c








In [ ]:
!pip install tweet-preprocessor

In [ ]:
!pip install rank_bm25

In [ ]:
import sys
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import json
from datetime import datetime
import pickle
import joblib
import re
import preprocessor as p
import pandas as pd 

In [ ]:
tf_idf = joblib.load("/content/drive/MyDrive/Colab Notebooks/IR/bengal_df.sav")

In [ ]:
tweets=tf_idf['text']
tf_idf['cleaned_tweet'] = tf_idf['text'].apply(p.clean)
data=tf_idf['cleaned_tweet']


data = data.astype(str).str.replace('\d+', '')
lower_text = data.str.lower()

new_words = []
for word in lower_text:
  new_word = re.sub(r'[^\w\s]', '', (word))
  if new_word != '':
      new_words.append(new_word)
print(new_words)
print(type(new_words))

df = pd.DataFrame(new_words) 



[' travesty of justice to see wb cm pay tribute to the martyrs of nandigram forget justice she gave ips satyajit bandopadhy', ' needs changethey need a government who can deliverin years failed to bring investment', 'budget on treadmillmanifesto on wheel chairnot a big deal', ' with sh tajinder pal singh bagga ji spokeperson bjp delhi and sh mangilal ji during west bengal ele', ' on this day in  innocent villagers were killed in firing at  many bodies could not be found it was a', ' bjp will protect the people education and culture of bengal from the dictatorial rule of tmc', ' said she is contesting from in to work along with', ' needs changethey need a government who can deliverin years failed to bring investment', ' young left candidates of give hope amid corrupt communal politics of  young leftists in bengal are t', ' with sh tajinder pal singh bagga ji spokeperson bjp delhi and sh mangilal ji during west bengal ele', ' election campaign starts at jamuria constituency', ' march   w

In [ ]:
df

0
0      travesty of justice to see wb cm pay tribute ...
1      needs changethey need a government who can de...
2     budget on treadmillmanifesto on wheel chairnot...
3      with sh tajinder pal singh bagga ji spokepers...
4      on this day in  innocent villagers were kille...
...                                                 ...
2448   with sh tajinder pal singh bagga ji spokepers...
2449                                       watch video 
2450   travesty of justice to see wb cm pay tribute ...
2451   march   will always be remembered a sombre da...
2452   needs changethey need a government who can de...

[2453 rows x 1 columns]

In [ ]:
corpus = []
df.columns = ['a']
# print(df.columns)
# corpus = df.loc['a']
new_words = df['a'].tolist()
print(corpus)

for x in new_words:
  temp = x.lstrip()
  # print(temp)
  corpus.append(temp)



In [ ]:
##############  REMOVING DUPLICATE ########################
r1=[]
c1 = corpus
for i in c1: 
    if i not in r1: 
        r1.append(i) 

print(len(r1))
r1

In [ ]:
###########################  MANUAL LABELLING THE TWEETS ##############################################

label1=[]
c=0
for x in r1:
  print(x)
  inpp = int(input("Enter 0 if tweet is neutral, 1 for moderate and 2 for extreme\n") )
  c=c+1
  if c%50==0:
      print("------------------------------" , c)

  
  print("\n")
  label1.append(inpp)

**DATA PREPROCESSING and MODEL IMPLEMENTATION**

Follwing are Machine Learning Models we used 

*   Multinomial Naive Bayes classifier
*   SVC (Support Vector Classifier)
*   Decision Tree 
*   Logistic Regression
*   Random Forest






In [ ]:
import pandas as pd
from tabulate import tabulate
from sklearn.naive_bayes import MultinomialNB
import pandas as pdo
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import svm
from sklearn.naive_bayes import BernoulliNB
import heapq 
from sklearn.svm import LinearSVC
from sklearn.utils import shuffle
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error
from sklearn import tree
import plotly.express as px
from sklearn.metrics import zero_one_loss
from tabulate import tabulate
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
import joblib
from sklearn import metrics
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import os
import scipy.io as sio
import re
import nltk
import pickle
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
data = pickle.load(open("/content/drive/MyDrive/Colab Notebooks/IR/w24", 'rb'))
# result = loaded_model.score(X_test, Y_test)
data = data.astype({"label":int})

In [ ]:
data1 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/IR/labell.csv")


In [ ]:
xx1 = data1['Tweets']
yy1 = data1['Labels']

In [ ]:
xx = d2[0]
yy = d2['label']

In [ ]:
xx = xx.append(xx1)
yy = yy.append(yy1)

In [ ]:

df = pd.DataFrame(list(zip(xx,yy)),columns=["Tweets","Label"])
data = df

In [ ]:
filename = 'finalized_dataset_1068.sav'
pickle.dump(data, open(filename, 'wb'))

In [ ]:
corpus = []
for i in range(0, 1068):
    review = data["Tweets"][i]
    review = review.split()
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]   ######## RemovingStopword
    review = ' '.join(review)
    corpus.append(review)

y = data['Label']

In [ ]:
len(corpus)

1068

In [ ]:

word2count = {} 
for datas in corpus: 
    words = nltk.word_tokenize(datas) 
    for word in words: 
        if word not in word2count.keys(): 
            word2count[word] = 1
        else: 
            word2count[word] += 1

print(len(word2count))

########################  WE TOOK ONLY 1500 FEATURES out of 1801 #################################
freq_words = heapq.nlargest(1500, word2count, key=word2count.get)
print(freq_words)

1801
['need', 'bengal', 'year', 'govern', 'bring', 'fail', 'invest', 'ji', 'deliverin', 'sh', 'bjp', 'changethey', 'justic', 'nandigram', 'west', 'cm', 'singh', 'day', 'march', 'delhi', 'peopl', 'mani', 'rememb', 'tajind', 'pal', 'bagga', 'spokeperson', 'mangil', 'kill', 'could', 'found', 'villag', 'fire', 'brother', 'innoc', 'bodi', 'mark', 'see', 'come', 'ip', 'forget', 'wb', 'gave', 'ele', 'martyr', 'satyajit', 'travesti', 'pay', 'tribut', 'bandopadhi', 'get', 'elect', 'develop', 'ki', 'baat', 'mamata', 'built', 'industri', 'agricultur', 'protectiontmc', 'amp', 'tmc', 'alway', 'sombr', 'date', 'solemnli', 'banerje', 'contest', 'everi', 'sister', 'want', 'video', 'join', 'observ', 'th', 'encourag', 'chang', 'give', 'india', 'parti', 'set', 'respect', 'lost', 'live', 'hope', 'candid', 'state', 'leader', 'didi', 'memori', 'campaign', 'youtub', 'attack', 'relief', 'mann', 'momtai', 'youwatch', 'longer', 'kolkata', 'away', 'one', 'support', 'stage', 'gandhi', 'ralli', 'vote', 'polit', 's

In [ ]:

X = [] 
for data in corpus: 
    vector = [] 
    for word in freq_words: 
        if word in nltk.word_tokenize(data): 
            vector.append(1) 
        else: 
            vector.append(0) 
    X.append(vector) 
X = np.asarray(X) 

In [ ]:
X_main=X
print(X.shape)


(1068, 1500)


In [ ]:
# cv = CountVectorizer(max_features = 1000)
# X = cv.fit_transform(corpus).toarray()
# y = data['Labels'].values

In [ ]:
from sklearn.model_selection import train_test_split


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
#################################  MULTINOMIAL NB #############################3

classifier = MultinomialNB(alpha=3)

# TRAINING
classifier.fit(X_train, y_train)

# Predicting
y_pred = classifier.predict(X_test)


cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix:\n",cm)

score1 = accuracy_score(y_test,y_pred)
# score2 = precision_score(y_test,y_pred)
# score3= recall_score(y_test,y_pred)
print("\n")
print(" Testing Accuracy is ",round(score1*100,2),"%")



y_pred1 = classifier.predict(X_train)


cm = confusion_matrix(y_train, y_pred1)
print ("Confusion Matrix:\n",cm)

score2 = accuracy_score(y_train,y_pred1)
# score2 = precision_score(y_test,y_pred)
# score3= recall_score(y_test,y_pred)
print("\n")
print("Accuracy is training ",round(score2*100,2),"%")


Confusion Matrix:
 [[96  5 21]
 [13 67 28]
 [11 16 96]]


 Testing Accuracy is  73.37 %
Confusion Matrix:
 [[198   4  24]
 [  9 200  26]
 [  8  27 219]]


Accuracy is training  86.29 %


In [ ]:
print(len(y_pred))

In [ ]:
###########################  SVC ###################################3

from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline
clf = make_pipeline(StandardScaler(), SVC(gamma='auto',kernel='rbf'))

# Training
clf.fit(X_train, y_train)
# Predicting
y_pred = clf.predict(X_test)

score1 = accuracy_score(y_test,y_pred)
# score2 = precision_score(y_test,y_pred)
# score3= recall_score(y_test,y_pred)
print("\n")
print("Accuracy is ",round(score1*100,2),"%")


y_pred1 = classifier.predict(X_train)


cm = confusion_matrix(y_train, y_pred1)
print ("Confusion Matrix:\n",cm)

score2 = accuracy_score(y_train,y_pred1)
# score2 = precision_score(y_test,y_pred)
# score3= recall_score(y_test,y_pred)
print("\n")
print("Accuracy is training ",round(score2*100,2),"%")



Accuracy is  75.92 %
Confusion Matrix:
 [[198   4  24]
 [  9 200  26]
 [  8  27 219]]


Accuracy is training  86.29 %


In [ ]:
##############################   DECISION TREE ###################################
from sklearn.tree import DecisionTreeClassifier


clf = DecisionTreeClassifier(criterion='entropy')
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

score1 = accuracy_score(y_test,y_pred)

print("\n")
print("Accuracy is ",round(score1*100,2),"%")


y_pred1 = clf.predict(X_train)


cm = confusion_matrix(y_train, y_pred1)
print ("Confusion Matrix:\n",cm)

score2 = accuracy_score(y_train,y_pred1)

print("\n")
print("Accuracy is training ",round(score2*100,2),"%")



Accuracy is  76.49 %
Confusion Matrix:
 [[226   0   0]
 [  5 230   0]
 [  0   4 250]]


Accuracy is training  98.74 %


In [ ]:
##########################  LOGISTIC REGRESSION ################################

from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg=logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)

score1 = accuracy_score(y_test,y_pred)

print("\n")
print("Accuracy is ",round(score1*100,2),"%")


y_pred1 = logreg.predict(X_train)


cm = confusion_matrix(y_train, y_pred1)
print ("Confusion Matrix:\n",cm)

score2 = accuracy_score(y_train,y_pred1)

print("\n")
print("Accuracy is training ",round(score2*100,2),"%")



Accuracy is  77.34 %
Confusion Matrix:
 [[225   1   0]
 [  6 229   0]
 [  0   7 247]]


Accuracy is training  98.04 %


In [ ]:
###############################  RANDOM FOREST ###############################

from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators = 100)
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

score1 = accuracy_score(y_test,y_pred)

print("\n")
print("Accuracy is ",round(score1*100,2),"%")


y_pred1 = clf.predict(X_train)


cm = confusion_matrix(y_train, y_pred1)
print ("Confusion Matrix:\n",cm)

score2 = accuracy_score(y_train,y_pred1)

print("\n")
print("Accuracy is training ",round(score2*100,2),"%")




Accuracy is  76.2 %
Confusion Matrix:
 [[226   0   0]
 [  5 229   1]
 [  0   3 251]]


Accuracy is training  98.74 %


In [ ]:
##############################  TEMPORARY WORK FOR FUTURE REFRENCE ############################

# import itertools
# import numpy as np

# from sklearn import svm, linear_model
# from sklearn.model_selection import cross_validate


# def transform_pairwise(X, y):
#     """Transforms data into pairs with balanced labels for ranking
#     Transforms a n-class ranking problem into a two-class classification
#     problem. Subclasses implementing particular strategies for choosing
#     pairs should override this method.
#     In this method, all pairs are choosen, except for those that have the
#     same target value. The output is an array of balanced classes, i.e.
#     there are the same number of -1 as +1
#     Parameters
#     ----------
#     X : array, shape (n_samples, n_features)
#         The data
#     y : array, shape (n_samples,) or (n_samples, 2)
#         Target labels. If it's a 2D array, the second column represents
#         the grouping of samples, i.e., samples with different groups will
#         not be considered.
#     Returns
#     -------
#     X_trans : array, shape (k, n_feaures)
#         Data as pairs
#     y_trans : array, shape (k,)
#         Output class labels, where classes have values {-1, +1}
#     """
#     X_new = []
#     y_new = []
#     y = np.asarray(y)
#     if y.ndim == 1:
#         y = np.c_[y, np.ones(y.shape[0])]
#     comb = itertools.combinations(range(X.shape[0]), 2)
#     for k, (i, j) in enumerate(comb):
#         if y[i, 0] == y[j, 0] or y[i, 1] != y[j, 1]:
#             # skip if same target or different group
#             continue
#         X_new.append(X[i] - X[j])
#         y_new.append(np.sign(y[i, 0] - y[j, 0]))
#         # output balanced classes
#         if y_new[-1] != (-1) ** k:
#             y_new[-1] = - y_new[-1]
#             X_new[-1] = - X_new[-1]
#     return np.asarray(X_new), np.asarray(y_new).ravel()


# class RankSVM(svm.LinearSVC):
#     """Performs pairwise ranking with an underlying LinearSVC model
#     Input should be a n-class ranking problem, this object will convert it
#     into a two-class classification problem, a setting known as
#     `pairwise ranking`.
#     See object :ref:`svm.LinearSVC` for a full description of parameters.
#     """

#     def fit(self, X, y):
#         """
#         Fit a pairwise ranking model.
#         Parameters
#         ----------
#         X : array, shape (n_samples, n_features)
#         y : array, shape (n_samples,) or (n_samples, 2)
#         Returns
#         -------
#         self
#         """
#         X_trans, y_trans = transform_pairwise(X, y)
#         super(RankSVM, self).fit(X_trans, y_trans)
#         return self

#     def predict(self, X):
#         """
#         Predict an ordering on X. For a list of n samples, this method
#         returns a list from 0 to n-1 with the relative order of the rows of X.
#         Parameters
#         ----------
#         X : array, shape (n_samples, n_features)
#         Returns
#         -------
#         ord : array, shape (n_samples,)
#             Returns a list of integers representing the relative order of
#             the rows in X.
#         """
#         if hasattr(self, 'coef_'):
#             np.argsort(np.dot(X, self.coef_.T))
#         else:
#             raise ValueError("Must call fit() prior to predict()")

#     def score(self, X, y):
#         """
#         Because we transformed into a pairwise problem, chance level is at 0.5
#         """
#         X_trans, y_trans = transform_pairwise(X, y)
#         return np.mean(super(RankSVM, self).predict(X_trans) == y_trans)


# if __name__ == '__main__':
#     # as showcase, we will create some non-linear data
#     # and print the performance of ranking vs linear regression

#     # np.random.seed(1)
#     # n_samples, n_features = 300, 5
#     true_coef = np.random.randn(1500)
#     # X = np.random.randn(n_samples, n_features)
#     # noise = np.random.randn(n_samples) / np.linalg.norm(true_coef)
#     # y = np.dot(X, true_coef)
#     # y = np.arctan(y) # add non-linearities
#     # y += .1 * noise  # add noise
#     # Y = np.c_[y, np.mod(np.arange(n_samples), 5)]  # add query fake id
#     # cv = cross_validation.KFold(n_samples, 5)
#     # train, test = iter(cv).next()

#     # # make a simple plot out of it
#     import pylab as pl
#     pl.scatter(np.dot(X, true_coef), y)
#     pl.title('Data to be learned')
#     pl.xlabel('<X, coef>')
#     pl.ylabel('y')
#     pl.show()

#     # print the performance of ranking
#     rank_svm = RankSVM().fit(X_train, y_train)
#     print ('Performance of ranking ', rank_svm.score(X_test,y_test))

#     # and that of linear regression
#     ridge = linear_model.RidgeCV(fit_intercept=True)
#     ridge.fit(X_train, y_train)
#     X_test_trans, y_test_trans = transform_pairwise(X_test,y_test)
#     score = np.mean(np.sign(np.dot(X_test_trans, ridge.coef_)) == y_test_trans)
#     print ('Performance of linear regression ', score)